# ansible-playbook \
#    -i inventarios/inventario-0.ini \
#    playbooks/instalacion.yaml \
#    --tags test \
#    --extra-vars '@playbooks/instalacion.vars.yaml'


-   hosts: all
    order: inventory
    
    gather_facts: True
    
    vars:
        vars_dir: "{{ playbook_dir }}/vars"
        herramientas: [] 
        nginx:
            port: 80
            serverName: "*"
            webPath: /www
            configPath: /etc/nginx/conf.d/nginx.conf
        
        test:
            timeout: 5
            delay: 2
            connect_timeout: 2
            urls:
                - protocol: http
                  url: /
                  statusCode: 200
    pre_tasks:
        -   include_tasks: tasks/pre_test.yaml # Variable INSTALAR= True False
            tags: 
                - instalacion
    tasks:
        -   include_tasks: tasks/instalaciones.yaml
            tags: 
                - instalacion
        -   include_tasks: tasks/configuracion.yaml
            tags: 
                - instalacion
                - configuracion
    post_tasks:
        -   include_tasks: tasks/test.yaml
            tags: 
                - instalacion
                - configuracion
                - test
        -   include_tasks: tasks/post_tasks.yaml
            tags: 
                - instalacion
                - configuracion
    handlers:
        -   import_tasks: handlers/configuracion.yaml

