---
instalador: 
    git:
        version:
            command: git --version
            requirements: [] 
        install:
            upgrade: true
            repo: 
                url: ppa:git-core/ppa
                key: ~

    curl:
        install:
            upgrade: false
        version:
            requirements: [] 

        #    command: curl --version

    nginx:
        upgrade: false
        version:
            command: "nginx -v 2>&1"
            requirements:
                - version: 1.13.4
                  comparator: ge
                - version: 1.14
                  comparator: lt
