- become: True
  block:
    - name: Buscar fichero de variables por defecto
      include_vars:
          dir: ../vars/
          files_matching: nginx.yaml
          #when: nginx is undefined
    
    - name: Fichero de configuracion de nginx
      template:
        dest: "{{ nginx.configPath }}"
        src: ../templates/nginx.template
        mode: 0444
      notify: CambioEnNginx

    - name: Cargar la pagina web
      #shell: "git clone {{ nginx.webSource }} {{ nginx.webPath }}"
      git: 
        repo: "{{ nginx.webSource }}"
        dest: "{{ nginx.webPath }}"
      notify: CambioEnNginx

    - name: Crujir la configuracion por defecto de nginx
      file: 
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: CambioEnNginx

    - name: Habilitar nginx al arranque de la maquina
      service:
        name: nginx
        enabled: True

    - name: Iniciar el servidor de nginx si no lo estaba ya
      service:
        name: nginx
        state: started

    - block:
        - name: Comprobar si tengo instalado ufw
          shell: "ufw --version"
          changed_when: False
          failed_when: False
          register: ufw_disponible
          
        - name: Firewall...ufw
          ufw:
            rule: allow
            port: "{{ nginx.port }}"
            proto: tcp
          when: ufw_disponible.rc == 0
          
      when: ansible_facts.distribution == "Ubuntu"

