
- name: Obtener versión de git
  shell: git --version
  register: gitVersion
  changed_when: False

- name: Obtener versión de nginx
  shell: nginx -v
  register: nginxVersion
  changed_when: False

- name: Obtener versión de la web
  #shell: |
  #  cd {{ webPath }}
  #  git rev-parse --short HEAD
  shell: "git rev-parse --short HEAD {{webPath}}"
  register: webVersion
  changed_when: False

- become: True
  block:
    - name: Generar custom fact 'installedVersions' 
      template:
        dest: /etc/ansible/fact.d/installedVersions.fact
        src: ../templates/installedVersions.json
        mode: 0444
      notify: CambioEnNginx

    - name: Generar custom fact 'currentVersions' 
      template:
        dest: /etc/ansible/fact.d/currentVersions.fact
        src: ../templates/currentVersions.sh
        mode: 0555
      notify: CambioEnNginx
