
- name: Obtener versión de git
  shell: git --version
  register: gitVersion
  changed_when: False

- name: Obtener versión de nginx
  shell: "nginx -v 2>&1"
  register: nginxVersion
  changed_when: False

- name: Obtener versión de la web
  #shell: |
  #  cd {{ webPath }}
  #  git rev-parse --short HEAD
  shell: "git --git-dir {{nginx.webPath}}/.git rev-parse --short HEAD "
  register: webVersion
  changed_when: False

- become: True
  block:
    - name: Crear directorio de custom fact
      file: 
        path: /etc/ansible/facts.d
        state: directory
    - name: Generar custom fact 'installedVersions' 
      template:
        dest: /etc/ansible/facts.d/installedVersions.fact
        src: ../templates/installedVersions.json
        mode: 0444
      notify: CambioEnNginx

    - name: Generar custom fact 'currentVersions' 
      template:
        dest: /etc/ansible/facts.d/currentVersions.fact
        src: ../templates/currentVersions.sh
        mode: 0555
      notify: CambioEnNginx
      
    - name: Generar custom fact 'currentVersions' en python 
      template:
        dest: /etc/ansible/facts.d/currentVersionsPy.fact
        src: ../templates/currentVersions.py
        mode: 0555
      notify: CambioEnNginx
