# ansible-playbook \
#    -i inventarios/inventario-0.ini \
#    playbooks/instalacion.yaml \
#    --tags test \
#    --extra-vars '@playbooks/instalacion.vars.yaml'


-   hosts: all
    order: inventory
    
    gather_facts: True
    
    vars:
        herramientas: [] 
        # OJO ESTO ES YAML... LISTA VACIA
    #var_files:
    #    - ./instalacion.vars.yaml
        
    pre_tasks:
        -   include_tasks: instalacion.variables.yaml
    tasks:
        -   include_tasks: instalacion.debian.yaml
    post_tasks:
        -   include_tasks: instalacion.test.yaml
    
    
# Tener cuidado con el SO
